version: "3.9"
services:
  web:
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://api.internal.local
  reverse-proxy:
    image: nginx:1.27-alpine
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/tls.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
