name: CI

on:
  push:
    branches: [ main, v1 ]
  pull_request:
    branches: [ main, v1 ]

jobs:
  build:
    runs-on: windows-latest
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      PLAYWRIGHT_CHANNEL: msedge
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: web/mcs-portal
        run: npm install

      - name: Lint
        working-directory: web/mcs-portal
        run: npm run lint

      - name: Format Check
        working-directory: web/mcs-portal
        run: npx prettier --check "src/**/*.{ts,tsx,css}"

      - name: Build
        working-directory: web/mcs-portal
        run: npm run build
